import = ["./everforest.toml"]
live_config_reload = true

[colors.primary]
background = "#1d1f21"
dim_foreground = "#828482"
foreground = "#c5c8c6"

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[cursor]
blink_interval = 500
[cursor.style]
blinking = "Always"


[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 12
y = 12
