tap "1password/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "koekeishiya/formulae"
brew "aria2"
brew "bat"
brew "cfonts"
brew "docker"
brew "exa"
brew "fd"
brew "fish"
brew "fisher"
brew "fnm"
brew "fzf"
brew "gawk"
brew "gh"
brew "ghq"
brew "git-delta"
brew "gnu-sed"
brew "iperf3"
brew "lazygit"
brew "mas"
brew "neofetch"
brew "neovim"
brew "onefetch"
brew "ripgrep"
brew "starship"
brew "telnet"
brew "tmux"
brew "wget"
brew "z"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
cask "1password"
cask "1password-cli"
cask "appcleaner"
cask "clashx"
cask "eudic"
cask "font-hack-nerd-font"
cask "karabiner-elements"
cask "keka"
cask "keycastr"
cask "logseq"
cask "notion"
cask "postman"
cask "raycast"
cask "telegram"
cask "visual-studio-code"
cask "wechat"
mas "Infuse", id: 1136220934
mas "OpenCat", id: 6445999201
mas "RunCat", id: 1429033973
mas "WeChat", id: 836500024
mas "Xnip", id: 1221250572
