gui:
  theme:
    lightTheme: false 
    activeBorderColor:
      - "#A7C080" # Green
      - bold
    inactiveBorderColor:
      - "#859289" # Text
    optionsTextColor:
      - "#7FBBB3" # Blue
    selectedLineBgColor:
      - "#343F44" # Surface0
    selectedRangeBgColor:
      - "#343F44" # Surface0
    cherryPickedCommitBgColor:
      - "#8bd5ca" # Teal
    cherryPickedCommitFgColor:
      - "#7FBBB3" # Blue
    unstagedChangesColor:
      - "#E67E80"       # Red
git:
  paging:
    colorArg: always
    # pager: diff-so-fancy
    pager: delta --dark --paging=never 
    # --24-bit-color=never --true-color=never
